# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

# For code coverage
r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'covr::coveralls()'

